#!/usr/bin/env zsh
# Load the script loader.
source `pwd`/bin/scripts/script.sh

# Source (import) specific scripts
# from a specific location.
script "temp"
script "trim"
script "pkg"
script "ols"

# Build time environment config.
NAME=`pkg ".name"`
VERSION=`pkg ".version"`
BUILD=`pkg ".build"`
BUILD_DIR=`pwd`/$BUILD
OUT="./$BUILD/$NAME"

# Ensure that the build directory exists.
if [ ! -d "$BUILD_DIR" ]; then
  mkdir $BUILD
else
  rm -rf $OUT &>/dev/null
fi

cmd="odin build ."
cmd="$cmd -out:$OUT"
cmd="$cmd -vet"
cmd="$cmd -strict-style"

len=`ols ".collections | length"`
for (( i=0; i<$len; i++ )); do
  n=`ols ".collections[$i].name"`
  p=`ols ".collections[$i].path"`

  cmd="$cmd -collection:$n=$p"
done

eval $cmd
